export const backgroundItemTable: string[][] = [
	[`C`, `printf("Hello World");`],
	[`C++`, `std::cout << "Hello World";`],
	[`COBOL`, `DISPLAY "Hello World".    .`],
	[`Scala`, `printIn("Hello World")`],
	[`MATLAB`, `disp('Hello World');`],
	[`C#`, `System.Console.WriteLine(\n  "Hello World"\n);`],
	[`CoffeeScript`, `console.lof 'Hello World'`],
	[`Delphi`, `WriteLn('Hello World');`],
	[`Dart`, `print('Hello World');`],
	[`Haskell`, `main = putStrLn "Hello World"`],
	[`Pascal`, `writeln ('Hello, world.');`],
	[`Ruby`, `puts 'Hello World'`],
	[`Python`, `print("Hello World")`],
	[`Assembly`, `db    'Hello World', 10, 0`],
	[`R`, `cat('Hello World')`],
	[`Swift`, `println('Hello World');`],
	[`Kotlin`, `println("Hello World")`],
	[`PHP`, `echo "Hello World";`],
	[`Java`, `System.out.println(\n  "Hello World"\n);`],
	[`Go`, `println('Hello World");`],
	[`F#`, `printfn "Hello World"`],
	[`Lisp`, `(print "Hello World")`],
	[`JavaScript`, `console.log("Hello World");`],
	[`Algol`, `BEGIN DISPLAY(\n  "Hello World"\n) \nEND.`],
	[`Perl`, `print "Hello World\\n";`],
	[`TCL`, `puts "Hello World"`],
	[`TypeScript`, `console.log 'Hello World'`],
	[`Fortran`, `print *, "Hello World"`],
	[`Bash`, `echo "Hello World"`],
	[`HTML`, `<h1>Hello World<h1>`],
	[`1C-Enterprise`, `Message("Hello, World!");`],
	[`4D`, `ALERT("Hello World!")`],
	[`4Test`, `print("Hello World!")`],
	[`ABAP4`, `WRITE: 'Hello world'.`],
	[`ABC`, `WRITE "Hello, World!" /`],
	[`ACPI Source Language`, `Store ("Hello World", Debug)`],
	[`ACS`, `print(s:"Hello World!");`],
	[`Action!`, `PrintE("Hello World!")`],
	[`Actionscript (Flash 5)`, `trace ("Hello World");`],
	[`Ada`, `Text_IO.Put_Line(\n  "Hello World!"\n);`],
	[`Agda`, `main = run\n  (putStrLn "Hello, World!")`],
	[`Algol-60`, `OUTPUT(\n  4,'(''('Hello World!')',/')'\n)`],
	[`Algol-68`, `print(\n  ("Hello World!",newline)\n)`],
	[`AMOS`, `Print "Hello world!"`],
	[`Andl`, `'Hello world!'`],
	[`APC`, `log ("Hello, world!\n");`],
	[`AppleScript`, `display dialog "Hello World"`],
	[`Arena`, `print("Hello World!");`],
	[`LaTeX`, `\\begin{document}\nHello World!\n\\end{document}`],
	[`Node.js`, `var sys = require('sys');\nsys.puts('Hello World');`],
	[`Rust`, `fn main() {\n  println!("Hello World");\n}`],
	[`Elixir`, `IO.puts "Hello World"`],
	[`Erlang`, `io:format("Hello World~n").`],
	[`Clojure`, `(println "Hello World")`],
	[`Julia`, `println("Hello World")`],
	[`Groovy`, `println 'Hello World'`],
	[`Objective-C`, `NSLog(@"Hello World");`],
	[`Lua`, `print("Hello World")`],
	[`Nim`, `echo "Hello World"`],
	[`Crystal`, `puts "Hello World"`],
	[`Zig`, `std.debug.print(\n  "Hello World\\n", .{}\n);`],
	[`OCaml`, `print_string "Hello World"`],
	[`Scheme`, `(display "Hello World")`],
	[`Prolog`, `:- write('Hello World'), nl.`],
	[`Smalltalk`, `Transcript show: 'Hello World'.`],
	[`VHDL`, `report "Hello World";`],
	[`Verilog`, `$display("Hello World");`],
	[`PowerShell`, `Write-Host "Hello World"`],
	[`SQL`, `SELECT 'Hello World';`],
	[`Visual Basic`, `Console.WriteLine(\n  "Hello World"\n)`],
	[`VBScript`, `MsgBox "Hello World"`],
	[`D`, `writeln("Hello World");`],
	[`V`, `println('Hello World')`],
	[`Vala`, `stdout.printf("Hello World\\n");`],
	[`Racket`, `(displayln "Hello World")`],
	[`Elm`, `main = text "Hello World"`],
	[`PureScript`, `main = log "Hello World"`],
	[`Idris`, `main = putStrLn "Hello World"`],
	[`Solidity`, `emit Log("Hello World");`],
	[`Raku`, `say "Hello World";`],
	[`Forth`, `." Hello World"`],
	[`APL`, `'Hello World'`],
	[`Fish`, `echo "Hello World"`],
	[`AWK`, `BEGIN { print "Hello World" }`],
	[`Brainfuck`, `++++++++[>++++[>++>+++\n>+++>+<<<<-]...]`],
	[`Standard ML`, `print "Hello World\\n";`],
	[`Eiffel`, `print ("Hello World%N")`],
	[`Modula-2`, `WriteString("Hello World");`],
	[`Oberon`, `Out.String("Hello World")`],
	[`PL/I`, `PUT LIST('Hello World');`],
	[`Rexx`, `say 'Hello World'`],
	[`Icon`, `write("Hello World")`],
	[`Logo`, `print [Hello World]`],
	[`BASIC`, `10 PRINT "Hello World"`],
	[`Haxe`, `trace("Hello World");`],
	[`GDScript`, `print("Hello World")`],
	[`AutoHotkey`, `MsgBox, Hello World`],
	[`Euphoria`, `puts(1, "Hello World")`],
	[`Boo`, `print "Hello World"`],
	[`Nemerle`, `System.Console.WriteLine(\n  "Hello World"\n);`],
	[`Mercury`, `io.write_string(\n  "Hello World", !IO\n)`],
	[`Oz`, `{Browse 'Hello World'}`],
	[`J`, `echo 'Hello World'`],
	[`Factor`, `"Hello World" print`],
	[`Tcsh`, `echo "Hello World"`],
	[`Coq`, `Compute "Hello World".`],
];
