export const backgroundItemTable: string[][] = [
	[`C`, `printf("Hello World");`],
	[`C++`, `std::cout << "Hello World";`],
	[`COBOL`, `DISPLAY "Hello World".    .`],
	[`Scala`, `printIn("Hello World")`],
	[`MATLAB`, `disp('Hello World');`],
	[`C#`, `System.Console.WriteLine(\n  "Hello World"\n);`],
	[`CoffeeScript`, `console.lof 'Hello World'`],
	[`Delphi`, `WriteLn('Hello World');`],
	[`Dart`, `print('Hello World');`],
	[`Haskell`, `main = putStrLn "Hello World"`],
	[`Pascal`, `writeln ('Hello, world.');`],
	[`Ruby`, `puts 'Hello World'`],
	[`Python`, `print("Hello World")`],
	[`Assembly`, `db    'Hello World', 10, 0`],
	[`R`, `cat('Hello World')`],
	[`Swift`, `println('Hello World');`],
	[`Kotlin`, `println("Hello World")`],
	[`PHP`, `echo "Hello World";`],
	[`Java`, `System.out.println(\n  "Hello World"\n);`],
	[`Go`, `println('Hello World");`],
	[`F#`, `printfn "Hello World"`],
	[`Lisp`, `(print "Hello World")`],
	[`JavaScript`, `console.log("Hello World");`],
	[`Algol`, `BEGIN DISPLAY(\n  "Hello World"\n) \nEND.`],
	[`Perl`, `print "Hello World\\n";`],
	[`TCL`, `puts "Hello World"`],
	[`TypeScript`, `console.log 'Hello World'`],
	[`Fortran`, `print *, "Hello World"`],
	[`Bash`, `echo "Hello World"`],
	[`HTML`, `<h1>Hello World<h1>`],
	[`1C-Enterprise`, `Message("Hello, World!");`],
	[`4D`, `ALERT("Hello World!")`],
	[`4Test`, `print("Hello World!")`],
	[`ABAP4`, `WRITE: 'Hello world'.`],
	[`ABC`, `WRITE "Hello, World!" /`],
	[`ACPI Source Language`, `Store ("Hello World", Debug)`],
	[`ACS`, `print(s:"Hello World!");`],
	[`Action!`, `PrintE("Hello World!")`],
	[`Actionscript (Flash 5)`, `trace ("Hello World");`],
	[`Ada`, `Text_IO.Put_Line(\n  "Hello World!"\n);`],
	[`Agda`, `main = run\n  (putStrLn "Hello, World!")`],
	[`Algol-60`, `OUTPUT(\n  4,'(''('Hello World!')',/')'\n)`],
	[`Algol-68`, `print(\n  ("Hello World!",newline)\n)`],
	[`AMOS`, `Print "Hello world!"`],
	[`Andl`, `'Hello world!'`],
	[`APC`, `log ("Hello, world!\n");`],
	[`AppleScript`, `display dialog "Hello World"`],
	[`Arena`, `print("Hello World!");`],
	[`LaTeX`, `\\begin{document}\nHello World!\n\\end{document}`],
	[`Node.js`, `var sys = require('sys');\nsys.puts('Hello World');`],
];
